//--- Dialog_ATM		
#define IDC_DIALOG_ATM_TEXT1					4972
#define IDC_DIALOG_ATM_TEXT2					4973
#define IDC_DIALOG_ATM_TEXTBANK					4974
#define IDC_DIALOG_ATM_TEXTCASH					4975
#define IDC_DIALOG_ATM_BACKGROUND				5172
#define IDC_DIALOG_ATM_EDITBOX					5372
#define IDC_DIALOG_ATM_LISTBOX					5472
#define IDC_DIALOG_ATM_BUTTONDEPOSIT			5572
#define IDC_DIALOG_ATM_BUTTONWITHDRAW			5573
#define IDC_DIALOG_ATM_BUTTONCLOSE				5574
#define IDC_DIALOG_ATM_BUTTONTRANSFER			5575

//--- Dialog_Inventory
#define IDC_DIALOG_INVENTORY_TITLE				14071
#define IDC_DIALOG_INVENTORY_WEIGHTTEXT			14072
#define IDC_DIALOG_INVENTORY_BACKGROUND			14271
#define IDC_DIALOG_INVENTORY_RSCPICTURE_1201	14272
#define IDC_DIALOG_INVENTORY_AMOUNT				14471
#define IDC_DIALOG_INVENTORY_ITEMLIST			14571
#define IDC_DIALOG_INVENTORY_PLAYERLIST			14572
#define IDC_DIALOG_INVENTORY_USEBUTTON			14671
#define IDC_DIALOG_INVENTORY_DROPBUTTON			14672
#define IDC_DIALOG_INVENTORY_GIVEBUTTON			14673
#define IDC_DIALOG_INVENTORY_CLOSEBUTTON		14674

//--- Dialog_Loading
#define IDC_DIALOG_LOADING_LOADINGTEXT			10359
#define IDC_DIALOG_LOADING_LOADINGHEADER		10360
#define IDC_DIALOG_LOADING_BACKGROUND			10459
#define IDC_DIALOG_LOADING_LOADINGBAR			11059

//--- Dialog_Shop
#define IDC_DIALOG_SHOP_AMOUNTTEXT				6684
#define IDC_DIALOG_SHOP_PRICETEXT				6685
#define IDC_DIALOG_SHOP_PRICEVALUETEXT			6686
#define IDC_DIALOG_SHOP_STOCKTEXT				6687
#define IDC_DIALOG_SHOP_STOCKVALUETEXT			6688
#define IDC_DIALOG_SHOP_ITEMNAMETEXT			6784
#define IDC_DIALOG_SHOP_BACKGROUND				6884
#define IDC_DIALOG_SHOP_AMOUNTEDIT				7084
#define IDC_DIALOG_SHOP_PURCHASEBUTTON			7284
#define IDC_DIALOG_SHOP_CLOSEBUTTON				7285

//--- Dialog_Level
#define IDC_DIALOG_LEVEL_RSCTEXT_1000			7752
#define IDC_DIALOG_LEVEL_RSCTEXT_1001			7753
#define IDC_DIALOG_LEVEL_TOTALXP				7754
#define IDC_DIALOG_LEVEL_FORNEXTLEVEL			7755
#define IDC_DIALOG_LEVEL_EXPERIENCETEXT			7852
#define IDC_DIALOG_LEVEL_LEVELTEXT				7853
#define IDC_DIALOG_LEVEL_NEXTLEVELTEXT			7854
#define IDC_DIALOG_LEVEL_BACKGROUND				7952
#define IDC_DIALOG_LEVEL_CLOSEBUTTON			8352
#define IDC_DIALOG_LEVEL_XPBAR					8552